//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.EFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int contId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<int> phone { get; set; }
        public string email { get; set; }
        public string address { get; set; }
    }
}
